[project]
name = "shared_utilities"
description = "My shared utilities package"
requires-python = ">=3.8"
dependencies = []
dynamic = ["version"]

[project.dynamic]
version = {attr = "src.__version__"}

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
