[project]
name = "shared_utilities"  # Name must be declared manually
dynamic = ["version"]       # <-- dynamical version
description = "My shared utilities package"
requires-python = ">=3.8"

[project.dynamic]
version = {attr = "src.__version__"} # <-- here is the version finder

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
